"""Public controls, input cancellation, responsive layout and fullscreen for two games."""
import os
from datetime import datetime, timezone
from pathlib import Path
from playwright.sync_api import sync_playwright, expect

base = os.environ.get('HOMEPAGE_TEST_URL', 'http://127.0.0.1:4173').rstrip('/')
out = Path('artifacts')
out.mkdir(exist_ok=True)
with sync_playwright() as p:
    browser = p.chromium.launch(executable_path=os.environ.get('HOMEPAGE_BROWSER', '/usr/bin/google-chrome'), args=['--no-sandbox'])
    errors = []
    context = browser.new_context(viewport={'width': 1440, 'height': 1000}, reduced_motion='reduce')
    page = context.new_page()
    page.on('pageerror', lambda e: errors.append(str(e)))
    page.add_init_script('Math.random = () => .999999')
    page.goto(base + '/games/huarongdao', wait_until='networkidle')
    for size in [3, 4, 5]:
        page.get_by_label('棋盘大小').select_option(str(size))
        expect(page.locator('.sliding-tile')).to_have_count(size * size - 1)
        expect(page.locator('.sliding-tile[tabindex="0"]')).to_have_count(1)
        page.locator('.sliding-tile[data-tile="1"]').dispatch_event('click')
        expect(page.locator('.game-stats strong').first).to_have_text('0')
        page.locator('.sliding-tile[data-tile="1"]').focus()
        page.keyboard.press('ArrowRight')
        expect(page.locator('.sliding-tile[data-tile="2"]')).to_be_focused()
        tile = page.locator(f'.sliding-tile[data-tile="{size * size - 1}"]')
        tile.focus()
        page.keyboard.press('Enter')
        expect(page.locator('.game-result')).to_contain_text('全部归位')
        expect(page.locator('.game-stats strong').first).to_have_text('1')
        page.get_by_role('button', name='撤销', exact=True).click()
        expect(page.locator('.game-result')).to_have_count(0)
        expect(page.locator('.game-stats strong').first).to_have_text('0')
        tile.click()
        expect(page.locator('.game-result')).to_contain_text('全部归位')
        page.get_by_role('button', name='重新开始', exact=True).click()
        expect(page.locator('.game-result')).to_have_count(0)
    context.close()

    context = browser.new_context(viewport={'width': 1440, 'height': 1000}, reduced_motion='reduce')
    page = context.new_page()
    page.on('pageerror', lambda e: errors.append(str(e)))
    now = datetime(2026, 1, 1, tzinfo=timezone.utc)
    page.clock.install(time=now)
    page.clock.pause_at(now)
    page.goto(base + '/games/jump', wait_until='networkidle')
    stage = page.locator('.jump-stage')
    stage.focus()
    page.keyboard.down('Space')
    page.clock.run_for(630)
    assert 50 <= int(page.get_by_role('meter').get_attribute('aria-valuenow')) <= 54
    page.keyboard.up('Space')
    expect(page.locator('.game-stats strong').first).to_have_text('1')
    expect(stage).to_have_attribute('data-phase', 'ready')
    page.get_by_role('button', name='重新开始', exact=True).click()
    stage.focus()
    page.keyboard.down('Space')
    page.clock.run_for(100)
    page.keyboard.up('Space')
    expect(page.locator('.game-stats strong').first).to_have_text('0')
    expect(page.locator('.game-result')).to_have_count(0)
    # Cancelled holds must never launch on the eventual keyup.
    for action in ['escape', 'blur', 'focus']:
        stage.focus()
        page.keyboard.down('Space')
        page.clock.run_for(600)
        if action == 'escape': page.keyboard.press('Escape')
        elif action == 'blur': page.evaluate('window.dispatchEvent(new Event("blur"))')
        else: page.get_by_role('button', name='重新开始', exact=True).focus()
        expect(stage).to_have_attribute('data-phase', 'ready')
        page.keyboard.up('Space')
        expect(page.locator('.game-stats strong').first).to_have_text('0')
    page.get_by_role('button', name='重新开始', exact=True).click()
    button = page.locator('.jump-hold')
    button.scroll_into_view_if_needed()
    box = button.bounding_box()
    page.mouse.move(box['x'] + box['width']/2, box['y'] + box['height']/2)
    page.mouse.down()
    page.clock.run_for(630)
    # Pointer capture handles releases outside the original button.
    page.mouse.move(box['x'] - 10, box['y'] - 10)
    page.mouse.up()
    expect(page.locator('.game-stats strong').first).to_have_text('1')
    page.get_by_role('button', name='重新开始', exact=True).click()
    stage.focus()
    page.keyboard.down('Enter')
    page.clock.run_for(3000)
    expect(page.get_by_role('meter')).to_have_attribute('aria-valuenow', '100')
    page.keyboard.up('Enter')
    expect(page.locator('.game-result')).to_contain_text('本局 0 分')
    page.get_by_role('button', name='重新开始', exact=True).click()
    page.locator('.header .brand').focus()
    page.keyboard.press('Space')
    expect(stage).to_have_attribute('data-phase', 'ready')
    context.close()

    context = browser.new_context(viewport={'width': 1440, 'height': 1000}, reduced_motion='reduce')
    page = context.new_page()
    page.on('pageerror', lambda e: errors.append(str(e)))
    for game in ['huarongdao', 'jump']:
        for theme in ['dark', 'light']:
            for width in [320, 390, 480, 481, 760, 768, 1024, 1051, 1440]:
                page.set_viewport_size({'width': width, 'height': 1000})
                page.goto(base + '/games/' + game, wait_until='networkidle')
                page.evaluate('(theme) => document.documentElement.dataset.theme = theme', theme)
                if game == 'huarongdao' and width == 320: page.get_by_label('棋盘大小').select_option('5')
                assert page.evaluate('document.documentElement.scrollWidth <= innerWidth'), (game, theme, width)
                expect(page.locator('.game-session-note')).to_be_visible()
                if width in [320, 390, 768, 1024, 1440]:
                    page.locator('.game-surface').screenshot(path=str(out / f'game-new-{game}-{theme}-{width}.png'))
        page.set_viewport_size({'width': 1440, 'height': 1000})
        page.goto(base + '/games/' + game, wait_until='networkidle')
        if game == 'huarongdao': page.locator('.sliding-tile.is-movable').first.click()
        before = page.locator('.game-stats').inner_text()
        scene = page.locator('.sliding-board' if game == 'huarongdao' else '.jump-stage')
        html = scene.inner_html()
        page.get_by_role('button', name='网页全屏', exact=True).click()
        for width, height in [(320,740), (390,844), (844,390), (1440,900)]:
            page.set_viewport_size({'width':width, 'height':height})
            page.wait_for_timeout(120)
            box = page.locator('.game-surface').bounding_box()
            assert box['x'] >= -1 and box['y'] >= -1 and box['x'] + box['width'] <= width + 1 and box['y'] + box['height'] <= height + 1, (game,width,box)
            assert scene.inner_html() == html
            assert page.locator('.game-stats').inner_text() == before
            if width in [390,844]: page.screenshot(path=str(out / f'game-new-{game}-fullscreen-{width}.png'))
        if game == 'jump': scene.focus()
        else: page.locator('.sliding-tile[tabindex="0"]').focus()
        page.keyboard.press('Escape')
        expect(page.get_by_role('button', name='网页全屏', exact=True)).to_be_focused()
        page.reload(wait_until='networkidle')
        expect(scene).to_be_visible()
    context.close()

    touch = browser.new_context(viewport={'width':390, 'height':844}, is_mobile=True, has_touch=True, reduced_motion='reduce')
    phone = touch.new_page()
    phone.on('pageerror', lambda e: errors.append(str(e)))
    phone.clock.install(time=now)
    phone.clock.pause_at(now)
    phone.goto(base + '/games/jump', wait_until='networkidle')
    phone.get_by_role('button', name='网页全屏', exact=True).tap()
    phone.locator('.jump-stage').scroll_into_view_if_needed()
    box = phone.locator('.jump-stage').bounding_box()
    session = touch.new_cdp_session(phone)
    point = {'x':box['x']+box['width']/2, 'y':box['y']+box['height']/2}
    session.send('Input.dispatchTouchEvent', {'type':'touchStart', 'touchPoints':[point]})
    phone.clock.run_for(400)
    session.send('Input.dispatchTouchEvent', {'type':'touchCancel', 'touchPoints':[]})
    expect(phone.locator('.jump-stage')).to_have_attribute('data-phase','ready')
    expect(phone.locator('.game-stats strong').first).to_have_text('0')
    session.send('Input.dispatchTouchEvent', {'type':'touchStart', 'touchPoints':[point]})
    phone.clock.run_for(630)
    session.send('Input.dispatchTouchEvent', {'type':'touchEnd', 'touchPoints':[]})
    expect(phone.locator('.game-stats strong').first).to_have_text('1')
    phone.goto(base + '/games/huarongdao', wait_until='networkidle')
    phone.locator('.sliding-tile.is-movable').first.tap()
    expect(phone.locator('.game-stats strong').first).to_have_text('1')
    touch.close()
    assert not errors, errors
    browser.close()
print('Sliding / jump browser passed: sorting, undo, pointer/keyboard/touch charge, cancellation, scoring, 9 widths, themes and fullscreen state/focus. Fresh screenshots: artifacts/game-new-*.png')
