export const profile = {
  name: 'a彬彬a',
  handle: 'zxabinbina',
  email: 'zxabinbina@mcyzw.top',
  github: 'https://github.com/zxabinbina',
  bilibili: 'https://b23.tv/jS91pO8',
  server: 'https://mcyzw.top',
  address: 'play.mcyzw.top',
}
export const projectCatalog = {
  checkedAt: '2026-10-04',
  organization: 'https://github.com/Youzai-World-Team',
}

export const projects = [
  {
    id: 'core',
    repository: 'Youzai-World-Team/YouzaiWorldCore',
    role: '团队项目',
    featured: true,
    image: 'youzaiworld-core.png',
    number: '01',
    title: 'YouzaiWorldCore',
    subtitle: '让方块世界，多一点可能。',
    description:
      '悠哉世界的核心模组。从自定义界面、传送锚点到宠物与成长系统，把想法变成可以游玩的体验。',
    tags: ['Java', 'Fabric', 'Minecraft'],
    url: 'https://github.com/Youzai-World-Team/YouzaiWorldCore',
    link: '探索源码',
    icon: 'youzai',
  },
  {
    id: 'web',
    repository: 'Youzai-World-Team/YouzaiWorldWebNew',
    role: '团队项目',
    featured: true,
    image: 'youzaiworld-web.webp',
    number: '02',
    title: 'Youzai World Web',
    subtitle: '一个世界，从这里开始。',
    description: '悠哉世界的官网，连接服务器动态、状态监控、下载与教程，让每一次出发都更简单。',
    tags: ['Vue / Nuxt', 'TypeScript', 'Rust'],
    url: 'https://mcyzw.top',
    link: '访问网站',
    icon: 'youzai',
  },
  {
    id: 'gaze',
    repository: 'zxaBinbina/gaze-zh-rdp-fix',
    role: '分支维护',
    featured: true,
    image: 'gaze.svg',
    number: '03',
    title: 'Gaze · 中文与登录修复',
    subtitle: '让日常使用，顺手一点。',
    description:
      '基于 Gaze 的源码分支，为 PAM 认证加入中文提示，并修复 KDE 远程桌面误触发本机人脸扫描的问题。',
    tags: ['Rust', 'Linux', 'PAM'],
    url: 'https://github.com/zxaBinbina/gaze-zh-rdp-fix',
    link: '探索源码',
    icon: 'scan',
  },
  {
    id: 'rdp',
    repository: 'zxaBinbina/rdp-access-auth',
    role: '个人项目',
    featured: true,
    image: 'rdp-access-auth.png',
    number: '04',
    title: 'RDP Access Auth',
    subtitle: '为远程连接，多守一道门。',
    description:
      '面向 SakuraFrp 远程桌面的网页认证入口，结合通行密钥与 IP 授权，让远程访问更从容。',
    tags: ['Python', 'WebAuthn', 'Cloudflare'],
    url: '/projects/rdp-access-auth',
    link: '官网与部署 Wiki',
    icon: 'shield',
  },
  {
    id: 'api',
    repository: 'Youzai-World-Team/YouzaiWorldApi',
    role: '团队项目',
    featured: false,
    image: '',
    number: '05',
    title: 'YouzaiWorldApi',
    subtitle: '连接世界背后的服务。',
    description: '悠哉世界服务器使用的 API 项目，为服务器相关功能提供接口支持。',
    tags: ['Vue', 'API'],
    url: 'https://github.com/Youzai-World-Team/YouzaiWorldApi',
    link: '探索仓库',
    icon: 'youzai',
  },
  {
    id: 'assets',
    repository: 'Youzai-World-Team/YouzaiWorldWebAssets',
    role: '团队项目',
    featured: false,
    image: '',
    number: '06',
    title: 'YouzaiWorldWebAssets',
    subtitle: '让网站素材各就各位。',
    description: '集中存放悠哉世界主站资源文件，用于同步到 Cloudflare。',
    tags: ['Shell', 'Cloudflare', '静态资源'],
    url: 'https://github.com/Youzai-World-Team/YouzaiWorldWebAssets',
    link: '探索仓库',
    icon: 'youzai',
  },
  {
    id: 'status',
    repository: 'Youzai-World-Team/YouzaiWorldServiceStatus',
    role: '团队项目',
    featured: false,
    image: '',
    number: '07',
    title: 'YouzaiWorldServiceStatus',
    subtitle: '关心每一次连接。',
    description: '检查悠哉世界相关服务的可用性，帮助了解服务是否正常运行。',
    tags: ['TypeScript', '状态监控'],
    url: 'https://github.com/Youzai-World-Team/YouzaiWorldServiceStatus',
    link: '探索仓库',
    icon: 'youzai',
  },
  {
    id: 'email',
    repository: 'Youzai-World-Team/YouzaiWorldDonaimEmailWorker',
    role: '团队项目',
    featured: false,
    image: '',
    number: '08',
    title: 'YouzaiWorldDonaimEmailWorker',
    subtitle: '打理域名下的往来。',
    description: '悠哉世界的域名邮件管理器，用于管理域名邮件。',
    tags: ['JavaScript', '邮件'],
    url: 'https://github.com/Youzai-World-Team/YouzaiWorldDonaimEmailWorker',
    link: '探索仓库',
    icon: 'youzai',
  },
  {
    id: 'modpack',
    repository: 'Youzai-World-Team/YouzaiWorldModpack',
    role: '团队项目',
    featured: false,
    image: '',
    number: '09',
    title: 'YouzaiWorldModpack',
    subtitle: '准备好，来世界里坐坐。',
    description: '存放悠哉世界服务器整合包的下载资源，方便玩家获取游玩所需的整合包。',
    tags: ['Minecraft', '整合包'],
    url: 'https://github.com/Youzai-World-Team/YouzaiWorldModpack',
    link: '探索仓库',
    icon: 'youzai',
  },
]

export const featuredProjects = projects.filter((project) => project.featured)
